name: setup_dart
description: The setup-dart GitHub Action - download and setup the Dart SDK.

publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  path: ^1.9.1
  pub_semver: ^2.2.0

dev_dependencies:
  args: ^2.7.0
  crypto: ^3.0.7
  dart_flutter_team_lints: ^3.5.2
